apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-ghcr
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 1.0.0
  secretRef:
    name: flux-oci
  url: oci://ghcr.io/sidd-harth/hw
