apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kust-oci
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: false
  sourceRef:
    kind: OCIRepository
    name: oci-ghcr
  targetNamespace: default
